spring:
  application:
    name: microservicecloud-zuul-gateway
server:
  port: 5555

zuul:
  # 多个 '*'
  ignoredServices: microservicecloud-item
  routes:
    users:
      path: /myitem/**
      serviceId: microservicecloud-item
  prefix: /ebuy

# 客户端注册进eureka服务列表内
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/,http://eureka6003.com:6003/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: microservicecloud-gateway-5555
    prefer-ip-address: true