server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/,http://eureka6003.com:6003/eureka/
    register-with-eureka: false
  instance:
    instance-id: microservicecloud-provider
    # lease-expiration-duration-in-seconds: 10
    # lease-renewal-interval-in-seconds: 10
